### ISSUE TITLE
Console error causing lots of lag

### ISSUE THREAD

**Issue by AssassinStingray** [BrassGoggledCoders/SteamCraft2#295]
[17:34:47] [Server thread/ERROR] [FML/]: A TileEntity type steamcraft.common.tiles.EmptyTiles$TileCrystal has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class steamcraft.common.tiles.EmptyTiles$TileCrystal is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by decebaldecebal** [comment]
This might be because the tile entity is not registered, since it is used only for model rendering.

**Comment by warlordjones** [comment]
Hrm, it should be registered, I'll have a look. That looks more like a NBT write error.

**Comment by decebaldecebal** [comment]
The tile entity doesn't have any methods, so that shouldn't be the case.However, I remember getting this error in the past when I forgot to register the entities.

**Comment by AssassinStingray** [comment]
Is that something that in need to fix or is something wrong with the code?

**Comment by decebaldecebal** [comment]
Something wrong with the code.

**Comment by AssassinStingray** [comment]
Okay, thank you for your fast responce!

**Comment by warlordjones** [comment]
I can't fix it at the moment, since I can't launch Eclipse/Smartgit D:

**Comment by decebaldecebal** [comment]
I can't work this weekend neither...Maybe after Tuesday I can start working again on fixing bugs.
