### ISSUE TITLE
issue with exnihilo

### ISSUE THREAD

**Issue by Horneat** [BrassGoggledCoders/Steamcraft2#343]
---- Minecraft Crash Report ----
// Oops.

Time: 30.11.15 20:35
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.RuntimeException: Invalid id 10428 - maximum id range exceeded.
	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:239)
	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:188)
	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:177)
	at exnihilo.registries.OreRegistry.registerOreBlock(OreRegistry.java:41)
	at exnihilo.registries.OreRegistry.createOre(OreRegistry.java:190)
	at exnihilo.registries.OreRegistry.createOverworldOre(OreRegistry.java:83)
	at exnihilo.registries.OreRegistry.createOverworldOre(OreRegistry.java:73)
	at exnihilo.compatibility.OreList.registerOres(OreList.java:47)
	at exnihilo.ExNihilo.PostInitialize(ExNihilo.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Invalid id 10428 - maximum id range exceeded.
	at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:379)
	at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:894)
	at cpw.mods.fml.common.registry.GameData.registerBlock(GameData.java:869)
	at cpw.mods.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:229)
	... 44 more

**Comment by accessdenied0** [comment]
Hi @Horneat,

Sorry to put me in, but your problem seem not to be Ex-Nihilo nor this Mod. If I may ask you if you recently added some mods or how many mods do you have? Because your available ID's just ran out. 
>> "invalid id 10428 - maximum id range exceeded."

access_denied
